In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('movie_rv.csv')
df

,Unnamed: 0,id,document,label
0,0,9976970,아 더빙.. 진짜 짜증나네요 목소리,0
1,1,3819312,흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나,1
2,2,10265843,너무재밓었다그래서보는것을추천한다,0
3,3,9045019,교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정,0
4,4,6483659,사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...,1
...,...,...,...,...
149995,149995,6222902,인간이 문제지.. 소는 뭔죄인가..,0
149996,149996,8549745,평점이 너무 낮아서...,1
149997,149997,9311800,이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?,0
149998,149998,2376369,청춘 영화의 최고봉.방황과 우울했던 날들의 자화상,1
149999,149999,9619869,한국 영화 최초로 수간하는 내용이 담긴 영화,0

In [3]:
# 긍부정 칼럼
df['label'].value_counts()

label
0    75173
1    74827
Name: count, dtype: int64

In [29]:
df_label_0 = df[df['label'] == 0]['document'].to_frame()

In [28]:
df_label_0

                                                 document
0                                     아 더빙.. 진짜 짜증나네요 목소리
2                                       너무재밓었다그래서보는것을추천한다
3                           교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정
5           막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화.ㅋㅋㅋ...별반개도 아까움.
6                                   원작의 긴장감을 제대로 살려내지못했다.
...                                                   ...
149990                                       이걸 영화라고 찎었냐?
149992  공포나 재난영화가 아니라 아예 대놓고 비급 크리쳐개그물임ㅋㅋ 음악 완전 흥겹다ㅋ 5...
149995                                인간이 문제지.. 소는 뭔죄인가..
149997                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?
149999                           한국 영화 최초로 수간하는 내용이 담긴 영화

[75173 rows x 1 columns]

In [32]:
positive_reviews = df[df['label'] == 1]['document']
negative_reviews = df[df['label'] == 0]['document']

# 긍정 리뷰에서 가장 많이 나타난 단어
positive_word_counts = Counter()
for review in positive_reviews:
    words = str(review).split()  # 문자열로 변환 후 분할
    positive_word_counts.update(words)

most_common_positive_word = positive_word_counts.most_common(1)[0][0]

# 부정 리뷰에서 가장 많이 나타난 단어
negative_word_counts = Counter()
for review in negative_reviews:
    words = str(review).split()  # 문자열로 변환 후 분할
    negative_word_counts.update(words)

most_common_negative_word = negative_word_counts.most_common(1)[0][0]

print("긍정 리뷰에서 가장 많이 나타난 단어:", most_common_positive_word)
print("부정 리뷰에서 가장 많이 나타난 단어:", most_common_negative_word)

긍정 리뷰에서 가장 많이 나타난 단어: 영화
부정 리뷰에서 가장 많이 나타난 단어: 영화

In [35]:
positive_reviews = []
negative_reviews = []
positive_word_counts = Counter()
negative_word_counts = Counter()

for index, row in df.iterrows():
    review = str(row['document'])  # 문자열로 변환
    words = review.split()
    if row['label'] == 1:
        positive_reviews.append(review)
        positive_word_counts.update(words)
    else:
        negative_reviews.append(review)
        negative_word_counts.update(words)

# 긍정 리뷰에서 가장 많이 나타난 단어 및 긍정 리뷰의 평균 길이
most_common_positive_word = positive_word_counts.most_common(1)[0][0]
positive_avg_length = sum(len(review.split()) for review in positive_reviews) / len(positive_reviews)

# 부정 리뷰에서 가장 많이 나타난 단어 및 부정 리뷰의 평균 길이
most_common_negative_word = negative_word_counts.most_common(1)[0][0]
negative_avg_length = sum(len(review.split()) for review in negative_reviews) / len(negative_reviews)

print("긍정 리뷰에서 가장 많이 나타난 단어:", most_common_positive_word)
print("긍정 리뷰의 평균 길이:", positive_avg_length)
print("부정 리뷰에서 가장 많이 나타난 단어:", most_common_negative_word)
print("부정 리뷰의 평균 길이:", negative_avg_length)

긍정 리뷰에서 가장 많이 나타난 단어: 영화
긍정 리뷰의 평균 길이: 7.507597524957569
부정 리뷰에서 가장 많이 나타난 단어: 영화
부정 리뷰의 평균 길이: 7.661926489564072